name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      name: Send request
      run: python3 main.py -l 'https://news.ycombinator.com/'
      name: Check if the file generated and has size
